### ISSUE TITLE
Any suggestions on running in this in the cloud?

### ISSUE THREAD

**Issue by rockyhuber** [spencermountain/dumpster-dive#80]
Space limitations on my new computer. With all the other binaries installed my computer is struggling to download and extract wikipedia. Any ideas on how to set this up in a cloud environment like Amazon?

**Comment by spencermountain** [comment]
hi Rox, yeah, i feel you. I was surprised my laptop could do it, to be honest.

yeah, it shouldn't be too hard to get a ec2 instance, install mongo, and do a `wget`, then `bzip2`.

i'd love to do this properly somehow - there are many people with more aws-foo than I do, but we should be able to do a one-liner to get a parsed mongodb install - especially if it was stored in the aws-cloud already, so no real downloads - or we could use dynamo instead of mongo.

All of it - we should do it all ;)
lemme know how it goes, and if you get somewhere, how we can help the next person.
cheers

**Comment by rockyhuber** [comment]
{ MongoNetworkError: connection 373 to localhost:27017 timed out
    at Socket.<anonymous> (/usr/local/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:335:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

I was first trying to run it from an external drive, it was very slow and the above error occurred ;(.
